apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
      - name: mlops
        image: aparnaapillai0coder/myapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000